//@version = 6

// █████╗ ██████╗ ██████╗ ███╗   ██╗ ██████╗
//██╔══██╗██╔══██╗██╔══██╗████╗  ██║██╔════╝
//███████║██████╔╝██████╔╝██╔██╗ ██║██║     
//██╔══██║██╔══██╗██╔══██╗██║╚██╗██║██║     
//██║  ██║██████╔╝██████╔╝██║ ╚████║╚██████╗
//╚═╝  ╚═╝╚═════╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝

indicator(title="EMA 20|50|100|200", overlay=true)

ema_20 = ta.ema(close, 20)
ema_50 = ta.ema(close, 50)
ema_100 = ta.ema(close, 100)
ema_200 = ta.ema(close, 200)

plot(ema_20, title = 'EMA 20',color=color.red)
plot(ema_50, title = 'EMA 500',color=color.orange)
plot(ema_100, title = 'EMA 100',color=color.green)
plot(ema_200, title = 'EMA 200',color=color.rgb(0, 140, 255))